### ISSUE TITLE
D Wrapper/Binding

### ISSUE THREAD

**Issue by MggMuggins** [Longhanks/qlift-c-api#1] opened 2017-07-15 20:12 UTC
D is as gorgeous a language as swift. I'd be interested in doing a D binding of this library. I don't have a whole lot of experience doing stuff like this, but calling C functions in D is about as easy as calling them in C++ (if not easier...). Do you have any advice on how I should proceed? Thanks a butt-ton.

**Comment by MggMuggins** [comment] 2017-07-15 21:10
Actually things are going fairly well. I got QObject and QWidget wrapped up really easily. I've basically been converting your Swift code to D. I'm running into a problem that is far beyond me though. In QCoreApplication, it grabs the command line args. In swift, that's really easy, because they are stored in variables that you can access from any part of your program. D is basically the same as C (except it just uses a dynamic array of strings). I'm not sure how to get those args into scope for QCoreApplication.

**Comment by Longhanks** [comment] 2017-07-15 22:46
The problem is that QCoreApplication takes the argc int _by reference_, something C has no knowledge of. If you pass in an int by value and it goes out of scope, the program will segfault when QCoreApplication tries to access that int.

For Qlift, I've solved it the following way: `QCoreApplication_new` takes an int by pointer (so an `int*` in C). This pointer gets dereferenced in `QCoreApplication_new` and it's value is passed to `QCoreApplication::operator new` (the C++ API). This prevents the segfaults as long as someone keeps the `int*` alive (which is the obligation of someone calling `QCoreApplication_new`.

In my Swift wrapper, I've added an instance variable to my QCoreApplication wrapper class that contains the argc integer. When creating a Swift instance of QCoreApplication, this int is allocated, `QCoreApplication_new`is passed the address of the instance variable and when the instance goes out of scope, the int is deallocated, thus preventing memory leaks, but keeping the int alive for as long as the underlying C++ instance is alive.

I must admit I have no idea whatsoever about D, so I can't really help you with how to implement this in it, but I hope this makes it a little clearer what is happening behind the curtains.

**Comment by Longhanks** [comment] 2017-07-15 22:50
Oh, and in my C example [(qlift-c-api-example)](https://github.com/Longhanks/qlift-c-api-example), I'm passing in the address of argc directly from main (via the reference operator `&`), maybe something like this can be done in D.

**Comment by MggMuggins** [comment] 2017-07-15 23:52
That C example is nice. The rule is that if you can do it in C, you can do it in D. And honestly, if you know C, you might like D. It's what C++ should have been, some have said.

Anyway, this is a slightly weird scenario. My code is here. ```this()``` is a constructor, and the ```this``` keyword can be used to reference members of a class from its methods (in this situation I could just reference argc and it would mean the same thing, but I like to use this for consistency).

Anyway, the first two lines of the constructor (clearly) assign the instance variable argc to the length of my arguments as passed via main, and create a new C-style mutable string to copy my D-style immutable string into. Then it prints something. The next 3.5 (awkward curly...) lines basically copy the D string array into the C-style string array. Then we print more stuff. At runtime, both prints are sucessful, and then I get a segfault. I'm sure this is some novice mistake, but I really am not sure what to do here...
![qcoreapp](https://user-images.githubusercontent.com/16041213/28243403-9166032a-698d-11e7-87c1-a905e607cfca.png)

Thanks for the help!

**Comment by Longhanks** [comment] 2017-07-20 10:55
Were you able to resolve the issue? I've reimplemented the memory management in qlift (Qt emits a signal when an object is about to be destroyed, I'm basically assigning a callback to that signal that "deletes" my Swift wrapper object: [code sample](https://github.com/Longhanks/qlift/commit/ceb88721a4e0f2024d44be6f998184013d43d95f)), maybe using a newer version of qlift-c-api (current is 0.0.33) will fix your problem.

I know the API is very unstable, but that's the current state of the project; I don't really have a design strategy in mind, I just try out things, see if they work. Sorry if that's an inconvenience. But the core QObject logic is in a state I'm very happy with (as memory management is pretty easy the way it is now), so I hope I don't have to change it very much in the future.

**Comment by MggMuggins** [comment] 2017-07-22 16:44
I changed the way things were working and I'm still confused. But I spent the last week at camp and so I need to go and look at my code to figure out what I did, and then possibly get back at it. We'll see.

**Closed as completed** 2017-08-07 15:03 UTC
